msg_api_herolo/msg_api_herolo/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('', include('msg_app.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('tinymce/', include('tinymce.urls')),
]

msg_api_herolo/msg_app/urls.py
from django.urls import path, reverse
from .views import (
    MessageCreateView,
    MessageDeleteView,
    )
from . import views

app_name = 'msg_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('messages/compose/', views.compose, name='compose'),
    path('messages/unread/', views.unread, name='unread'),
    path('messages/<int:pk>/', views.show_msg, name='show_msg'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='delete_msg'),
    path('messages/new/', MessageCreateView.as_view(), name='new_msg'),
]

msg_api_herolo/users/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.register_request, name='register_request'),
    path('login/', views.login_request, name='login_request'),
    path('logout/', views.logout_request, name='logout_request'),
]

msg_api_herolo/msg_app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

# Create your models here.
class Message(models.Model):
	subject = models.CharField(max_length=100)
	sender = models.CharField(max_length=50)
	receiver = models.CharField(max_length=50)
	creation_date = models.DateTimeField('creation date', default=datetime.now())
	content = models.TextField()
	read = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = 'Messages'

	def __str__(self):
		return self.subject

	def get_absolute_url(self):
		return reverse('msg_app:home')

msg_api_herolo/users/models.py
from django.db import models

# Create your models here.

msg_api_herolo/msg_app/forms.py
from django import forms
from tinymce.models import HTMLField
from datetime import datetime

# Create your models here.
class MessageForm(forms.Form):
	subject = forms.CharField(max_length=100)
	sender = forms.CharField(max_length=50)
	receiver = forms.CharField(max_length=50)
	# creation_date = forms.DateTimeField('creation date', default=datetime.now())
	content = HTMLField()

	class Meta:
		verbose_name_plural = 'Messages'

	def __str__(self):
		return self.subject

	def get_absolute_url(self):
		return reverse('msg_app:home')

msg_api_herolo/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

msg_api_herolo/msg_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
	LoginRequiredMixin,
	UserPassesTestMixin,
	)
from django.views.generic import (
	CreateView,
	DeleteView,
	)
from django.db import models
from .models import Message

# Create your views here.
def home(request):
	context = {'msgs':[]}
	for msg in Message.objects.all():
		# Checks if the message if the receiver or the sender is the current logged in user - 
		# if the message does not belong to one of the above - it is not included in the context
		if str(request.user) == msg.sender or str(request.user) == msg.receiver:
			context['msgs'].append(msg)
	return render(request=request, 
				  template_name='msg_app/home.html', 
				  context=context)


@login_required
def compose(request):
	return render(request=request,
				  template_name='msg_app/compose.html')


@login_required
def unread(request):
	context = {'msgs':[]}
	for msg in Message.objects.all():
		# Checks if the message was already read and if the receiver is the current logged in user - 
		# if the message was read, or the user is not the current logged in - the message is not included in the context
		if not msg.read and str(request.user) == msg.receiver:
			if str(request.user) == msg.sender or str(request.user) == msg.receiver:
				context['msgs'].append(msg)
	return render(request=request, 
				  template_name='msg_app/home.html', 
				  context=context)


@login_required
def delete_msg(request, pk):
	if request.method == 'POST':
		msg = Message.objects.get(pk=pk)
		msg_sender = msg.sender
		msg_receiver = msg.receiver
		# Deletes the message only if the message is owned by the current logged in user
		if str(request.user) == msg_sender or str(request.user) == msg_receiver:
			msg_subject = msg.subject
			msg_creation_date = msg.creation_date
			msg.delete()
			messages.success(request, f'Message {msg_subject} from {msg_sender} to {msg_receiver} sent on {msg_creation_date} was deleted successfully!')
		else:
			messages.error(request, f'You have no permission to delete the message for {msg_sender} or {msg_receiver} because you are logged in as {request.user}')
	return redirect('msg_app:home')

@login_required
def show_msg(request, pk):
	if request.method == 'GET':
		msg = Message.objects.get(pk=pk)
		msg_sender = msg.sender
		msg_receiver = msg.receiver
		# Shows the message only if the sender or the receiver is the current logged in user
		if str(request.user) == msg_sender or str(request.user) == msg_receiver:
			msg_subject = msg.subject
			msg_creation_date = msg.creation_date
			if str(request.user) == msg_receiver:
				msg.read = True
				msg.save()
			return render(request=request,
						  template_name='msg_app/show_msg.html',
						  context={'msg': msg})


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Message
	success_url = '/'
	def test_func(self):
		msg = self.get_object()
		if str(self.request.user) == msg.sender or str(self.request.user) == msg.receiver:
			return True
		return False


class MessageCreateView(LoginRequiredMixin, CreateView):
	model = Message
	fields = ['subject', 'receiver', 'content']
	def form_valid(self, form):
		form.instance.sender = self.request.user
		return super().form_valid(form)

msg_api_herolo/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import UserRegistrationForm

# Create your views here.
def register_request(request):
	if request.method == 'POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account for {username} was created!')
			login(request, user)
			return redirect('msg_app:home')
		else:
			for msg in form.error_messages:
				messages.error(request, f'{msg}: {form.error_messages[msg]}')
	form = UserRegistrationForm()
	return render(request=request,
				  template_name='users/register.html',
				  context={'form': form})


def login_request(request):
	if request.method == 'POST':
		form = AuthenticationForm(request=request, data=request.POST)
		if form.is_valid():

			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)

			if user is not None:
				messages.success(request, f'You were successfuly logged in as {username}!')
				login(request, user)
				return redirect('msg_app:home')
			else:
				messages.error(request, 'Invalid username or password!')
		else:
			for msg in form.error_messages:
				messages.error(request, f'{msg}: {form.error_messages[msg]}')

	form = AuthenticationForm()
	return render(request=request,
				  template_name='users/login.html',
				  context={'form': form}
				  )

def logout_request(request):
	logout(request)

	messages.info(request, f'You were logged out successfuly!')

	return redirect('msg_app:home')

msg_api_herolo/msg_app/templates/msg_app/app_theme.html
<head>
	{% load static %}
    <title>Messaging App</title>
    <link rel="shortcut icon" href="{% static 'msg_app/img/favicon_small.ico' %}" />
 	  <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Messaging <strong>App</strong></a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
      	{% include 'msg_app/includes/navbar_items.html' %}
      </ul>
    </div>
  </nav>
	  
  <ul class="sidenav" id="mobile-demo">
    {% include 'msg_app/includes/navbar_items.html' %}
  </ul>
  {% include 'msg_app/includes/messaging.html' %}
  <div class="container">
  	{% block content %}
  	{% endblock %}
  </div>
</body>

<script src="{% static 'tinymce/js/prism.js' %}"></script>
<script>M.AutoInit();</script>

msg_api_herolo/msg_app/templates/msg_app/home.html
{% extends "msg_app/app_theme.html" %}
{% block content %}
	{% if user.is_authenticated %}
		<table class="table mb-0">
			<thead>
				<tr>
					<th>Subject</th>
					<th>Sender</th>
					<th>Receiver</th>
					<th>Creation Date</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% if msgs %}
					{% for msg in msgs %}
						<tr>
							{% if not msg.read %}
								<td style="color: red">{{msg.subject}}</td>
							{% else %}
								<td style="color: green">{{msg.subject}}</td>
							{% endif %}

							<td>{{msg.sender}}</td>

							<td>{{msg.receiver}}</td>

							<td>{{msg.creation_date}}</td>

							<td><a href="{% url 'msg_app:show_msg' msg.id %}" class="btn btn-primary btn-sm">Read</a></td>						
							<td><a href="{% url 'msg_app:delete_msg' msg.id %}" class="btn btn-danger btn-sm">Delete</a></td>
					{% endfor %}
				{% endif %}
			</tbody>
		</table>
		<p>
			<a href="{% url 'msg_app:new_msg' %}" class="btn btn-primary">Compose</a>
		</p>
	{% else %}
		<h4>You need to login first to view messages...</h4>
		<br>
		<br>
		<br>
		<div class="border-top" pt-3>
			<small class="text-mutted"><a class="ml-2" href="{% url 'users_app:login_request' %}"><strong>Login</strong></a> or<a class="ml-2" href="{% url 'users_app:register_request' %}"><strong>Register</strong></a></small>
		</div>
	{% endif %}
{% endblock %}

msg_api_herolo/msg_app/templates/msg_app/includes/messaging.html
{% if messages %}
	{% for message in messages %}
		{% if message.tags == 'success' %}
			<script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:3000});</script>
		{% elif message.tags == 'info' %}
			<script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:3000});</script>
		{% elif message.tags == 'warning' %}
			<script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength: 3000});</script>
		{% elif message.tags == 'error' %}
			<script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength: 5000});</script>
		{% endif %}
	{% endfor %}
{% endif %}

msg_api_herolo/msg_app/templates/msg_app/includes/navbar_items.html
{% if user.is_authenticated %}
	<li><a href="/">My Messages</a></li>
	<li><a href="{% url 'msg_app:unread' %}">My Unread Messages</a></li>
	<li><a href="{% url 'msg_app:new_msg' %}">Compose</a></li>
	<li>Logged in as : <strong>{{user.username|title}}</strong></li>
	<li><a href="{% url 'users_app:logout_request' %}">Logout</a></li>
{% else %}
	<li><a href="{% url 'users_app:register_request' %}">Register</a></li>
	<li><a href="{% url 'users_app:login_request' %}">Login</a></li>
{% endif %}

msg_api_herolo/msg_app/templates/msg_app/message_confirm_delete.html
{% extends "msg_app/app_theme.html" %}
{% block content %}
    <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
          	<legend class="border-bottom mb-4">Delete Post</legend>
          	<h2>Delete the "{{object.subject}}" message to {{object.receiver}}?</h2>
          </fieldset>
          <div class="form-group">
          	<button type="submit" class="btn btn-outline-denger">Confirm</button>
          	<a class="btn btn-outline-secondary" href="{% url 'msg_app:show_msg' object.id%}">Cancel</a>
          </div>
    </form>
{% endblock %}

msg_api_herolo/msg_app/templates/msg_app/message_detail.html
{% extends "msg_app/app_theme.html" %}
{% block content %}
  <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{object.subject}}</span>
          <li><strong>From: </strong>{{object.sender}}</li>
          <li><strong>To: </strong>{{object.receiver}}</li>
          <li><strong>Sent on: </strong>{{object.creation_date}}</li>
          <p>{{object.content|safe}}</p>
      </div>
    </div>
  </div>
{% endblock %}

msg_api_herolo/msg_app/templates/msg_app/message_form.html
{% extends "msg_app/app_theme.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h4>New Message</h4>
    <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <br>
          <button type="submit" class="btn btn_primary">Send</button>
    </form>
{% endblock %}

msg_api_herolo/msg_app/templates/msg_app/message_list.html
{% extends "msg_app/app_theme.html" %}
{% block content %}
{% if user.is_authenticated %}
	<table class="table mb-0">
		<thead>
			<tr>
				<th>Subject</th>
				<th>Sender</th>
				<th>Receiver</th>
				<th>Creation Date</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for msg in msgs %}
				<tr>
					<td>{{msg.subject}}</td>

					<td>{{msg.sender}}</td>

					<td>{{msg.receiver}}</td>

					<td>{{msg.creation_date}}</td>

					<td><a href="{% url 'msg_app:show_msg' msg.id %}" class="btn btn-primary btn-sm">Read</a></td>

					<td><a href="#delete_conf_modal" class="waves-effect waves-light btn modal-trigger" style="background-color: #900500; color: white">Delete</a></td>

					<div id="delete_conf_modal" class="modal">

						<div class="modal-content">
							<h4>Are you sure you want to delete this message?</h4>
						</div>

						<div class="modal-footer">
							<form method="post" action="{% url 'msg_app:delete_msg' msg.pk %}">
								{% csrf_token %}
								<button type="submit" class="modal-close waves-effect waves-red btn-flat">Confirm
								</button>
								<a href="#!" class="modal-close waves-effect waves-green btn-flat">
								Cancel</a> 
							</form>
						</div>

					</div>

				</tr>
			{% endfor %}
		</tbody>
	</table>
	<p>
		<a href="{% url 'msg_app:new_msg' %}" class="btn btn-primary">Compose</a>
		<a href="{% url 'msg_app:read_all' %}" class="btn btn-primary">Read All</a>
		<a href="{% url 'msg_app:read_all' %}" class="btn btn-primary">Get Unread</a>
	</p>
{% else %}
	<h4>You need to login first to view messages...</h4>
	<br>
	<br>
	<br>
	<div class="border-top" pt-3>
		<small class="text-mutted"><a class="ml-2" href="{% url 'users_app:login_request' %}"><strong>Login</strong></a> or<a class="ml-2" href="{% url 'users_app:register_request' %}"><strong>Register</strong></a></small>
	</div>
{% endif %}	
{% endblock %}

msg_api_herolo/msg_app/templates/msg_app/show_msg.html
{% extends "msg_app/app_theme.html" %}
{% block content %}
  <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{msg.subject}}</span>
          <li><strong>From: </strong>{{msg.sender}}</li>
          <li><strong>To: </strong>{{msg.receiver}}</li>
          <li><strong>Sent on: </strong>{{msg.creation_date}}</li>
          <p>{{msg.content|safe}}</p>
      </div>
      <a href="{% url 'msg_app:unread' %}" class="btn btn-primary btn-sm">Unread</a>
      <a href="{% url 'msg_app:delete_msg' msg.id %}" class="btn btn-danger btn-sm">Delete</a>
    </div>
  </div>
{% endblock %}

msg_api_herolo/users/templates/users/login.html
{% extends 'msg_app/app_theme.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Login here: </legend>
				{{form|crispy}}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Login</button>
			</div>
		</form>
		<div class="border-top" pt-3>
			<small class="text-mutted">Don't have an account ? <a class="ml-2" href="{% url 'users_app:register_request' %}"><strong>Sign up</strong></a> now!</small>
		</div>
	</div>
{% endblock content %}

msg_api_herolo/users/templates/users/register.html
{% extends 'msg_app/app_theme.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Register here : </legend>
				{{form|crispy}}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">
					Register
				</button>
			</div>
		</form>
		<div class="border-top" pt-3>
			<small class="text-mutted"> Already have an account? <a class="ml-2" href="{% url 'users_app:login_request' %}"><strong>Login</strong></a> instead</small>
		</div>
	</div>
{% endblock content %}